export const videoList = {
    // assassinsCreed: [
    //     'gfycat:SecretBriskChital',
    //     'gfycat:RegularCanineGerbil',
    //     '',
    //     '',
    //     '',
    //     '',
    //     '',
    //     '',
    //     '',
    //     '',
    //     '',
    //     '',
    //     '',
    //     '',
    //     '',
    // ],
    breathOfTheWild: [
        'reddit:6wgxdoaa7mcb1',
        'reddit:aw2plrwx946b1',
        'reddit:n0ajnblq013b1',
        'reddit:gz9qlkmzpm3b1',
        'reddit:pyvwgeej4pza1',
        'reddit:g0muesbit25b1',
        'reddit:1h5vegvl4fab1'

    ],
    battlefield: [
        'gfycat:AgileMeekIrukandjijellyfish',
        'imgur:3ykvWne',
        'imgur:kMgCYt5',
        'gfycat:AcademicTemptingEnglishpointer',
        'gfycat:JampackedMediumBird',
        'imgur:DqJWQlm',
        'imgur:sYd7PUS',
        'gfycat:UnawareGlamorousHousefly',
        'gfycat:ForcefulEasyHuia',
        'gfycat:HardtofindHarmlessArgali',
        'gfycat:WarmBrilliantGazelle',
        'gfycat:FlawedEnviousAlleycat',
        'gfycat:JealousOffbeatCrossbill',
        'gfycat:BlankLightheartedKite',
        'gfycat:ShockedBlackEastsiberianlaika',
        'gfycat:NegativeSpiritedGrassspider',
        'gfycat:PerkyEcstaticChevrotain',
        'gfycat:InsignificantInferiorFoxterrier',
        'gfycat:GeneralArcticAffenpinscher',
        'gfycat:SkinnyTiredDarwinsfox',
        'gfycat:QuarterlyEachCardinal',
        'gfycat:HastyAppropriateLangur',
        'gfycat:GlamorousBlueHadrosaurus',
        'gfycat:EthicalIdenticalBeetle',
        'imgur:wlb5aEa',
        'imgur:SYqnJR7',
        'imgur:sLMxlK2',
        'imgur:vMvk8Ci',
        'imgur:J1onlCP',
        'imgur:j5aYgJ6',
        'imgur:wj628Nk',
        'imgur:1L01II3',
        'imgur:NZTG27C',
        'imgur:U2ZAGKM',
        'imgur:8m0aTTz',
        'imgur:VY12dlz',
        'imgur:IJRVRzg',
        'imgur:o1DbHlN',
        'imgur:RsKfZHk',
        'imgur:95dy2hp',
        'imgur:ePVzoBF',
        'imgur:CDtXlBw',
        'imgur:3SFL1Pr',
        'imgur:vBqZjZ3',
        'imgur:06R1wpE',
        'imgur:2YKU4iF',
        'imgur:hAq7dFi',
        'imgur:L4EVvzc',
        'imgur:Un2rXpB',
        'imgur:CPd1lN1',
        'imgur:qjRffmI',
        'imgur:FUnSDtc',
        'imgur:lP46f8Z',
        'imgur:d8Lw3Y2',
        'imgur:i0S8vJf',
        'imgur:NsGPqLE',
        'imgur:h9F3JBy',
        'imgur:Nf93jHe',
        'imgur:Cn6IFnQ',
        'imgur:ia7spnz',
        'imgur:lfw7gmv',
        'imgur:zvGkLfc',
        'imgur:WWChDhg',
        'imgur:xCLsYOi',
        'imgur:hJRdcqM',
        'imgur:sj7ydGF',
        'imgur:oFg7ljT',
        'imgur:iH4XEs2',
        'imgur:8AJR1wA',
        'imgur:2HRSzFO',
        'imgur:jGbSdlV',
        'imgur:WGwEHvO',
        'imgur:8uJLRBu',
        'imgur:dzm8C5X',
        'imgur:w6M4RNT',
        'imgur:musuCd6',
        '',
        '',




    ],
    cuphead: [
        'imgur:6tVdRp3',
        'gfycat:MediumWindingChrysomelid',
        'gfycat:ElderlySecretCicada',
        'gfycat:MeagerVengefulGrison',
        'gfycat:QuestionableColorfulBoilweevil',
        'gfycat:ThirstyDizzyCreature',
        'gfycat:LinearInsistentCooter',

    ],
    darkSouls: [
        'imgur:lr1tQRS',
        'gfycat:SandySpryArchaeopteryx',
        'imgur:EQO9X8p',
        'gfycat:InformalSecondhandAngelfish',
        'gfycat:EachMiniatureHectorsdolphin',
        'gfycat:ShallowFeistyAmericanbulldog',
        'gfycat:PeskyMasculineAbalone',
        'gfycat:PepperyLiquidLadybug',
        'gfycat:WealthyElectricDarwinsfox',
        'gfycat:FittingUnsightlyBarasingha',
        'gfycat:UnhealthyHauntingEarthworm',
        'gfycat:ReflectingMindlessDanishswedishfarmdog',
        'gfycat:GregariousImpeccableLabradorretriever',
        'gfycat:VioletWholeHartebeest',
        '',
        '',

    ],
    fallout: [
        'imgur:RuWFo6B',
        'gfycat:AmazingRequiredAmericanbobtail',
        'imgur:xYsCgmu',
        'imgur:YJtq0zB',
        'gfycat:SpitefulSoulfulFlatfish',
        'gfycat:SecondSafeAustralianshelduck',
        'gfycat:EnchantedWhiteHornedviper',
        'gfycat:CreepyLameFulmar',
        'gfycat:DefiantRareCondor',
        'gfycat:FarBitterAfricanrockpython',
        'gfycat:LonelyEsteemedBellfrog',
        'gfycat:CelebratedFlickeringBuck',
        '',
        '',
        '',
        '',
        '',


    ],
    forzaHorizon: [
        'gfycat:ShinyVigorousCats',
        'gfycat:BonyImportantGoral',
        'gfycat:MediumApprehensiveAustraliancattledog',
        'gfycat:JampackedMilkyAndeancat',
        'gfycat:PalatableFineAnura',
        'gfycat:InfatuatedShockedGoat',
        'gfycat:BitesizedSameAmericanriverotter',
        'gfycat:ImpassionedMindlessElephantseal',
        'gfycat:CoordinatedSharpCaecilian',
        'gfycat:VelvetyWiltedErmine',
        'gfycat:FatherlyPerfectDiscus',
        'gfycat:ZealousSelfreliantKawala',
        'gfycat:DangerousAbleEasteuropeanshepherd',
        'gfycat:TatteredSpecificAfricanwildcat',
        'reddit:xhp7mfw69j781',
        'reddit:xf3x55bsjv081',
        'reddit:q3l0sqsc38f61',
        'reddit:nnwocunstky71',
        'reddit:kemhdrey5l881',
        'reddit:hqfu2vjau1z71',
        'reddit:li7so63qa1681',
        'reddit:jbnn3n53vho81',
        'reddit:gtl93l94tx081',
        'reddit:3s6vpsmhsqma1',
        '',
        '',
        '',
        '',
        '',

    ],
    ghostRecon_Wildlands: [

        'imgur:A668H16',
        'gfycat:UnawareShadyCrownofthornsstarfish',
        'gfycat:PaleHandyAidi',
        'gfycat:AridFarflungFieldmouse',
        'gfycat:CavernousIdioticAmericancrayfish',
        'imgur:5OaANDn',
        'gfycat:DarlingDangerousChicken',
        'imgur:CdDAc5h',
        'imgur:vPnVIwO',
        'gfycat:InsistentSentimentalBufeo',
        '',
        '',
        '',
        '',

    ],
    grandTheftAuto: [
        'imgur:k7gQ66O',
        // 'gfycat:DesertedExcitableBordercollie',
        'gfycat:AgreeableConfusedKite',
        'gfycat:HotHandmadeEasternnewt',
        'gfycat:ShabbyComposedBelugawhale',
        'gfycat:RecklessLikelyBirdofparadise',
        
        

        'imgur:uNk5woD',
        'gfycat:ForsakenNervousCorydorascatfish',
        'gfycat:FarWhimsicalCivet',
        'imgur:xuxS3DN',
        'gfycat:SimilarOpulentAnemone',
        'gfycat:PepperySentimentalGraywolf',
        'gfycat:SnappyAppropriateAustraliancurlew',
        'imgur:0qnfTk9',
        'gfycat:DirectMassiveHawaiianmonkseal',
        'imgur:YSo4hkD',
        'gfycat:UnknownSparseHoneyeater',
        'gfycat:FancyThinHorse',
        'imgur:4iVHDZk',
        'imgur:eF5Yt8H',
        'gfycat:FrayedGoldenGorilla',
        'imgur:vWhHAgV',
        'gfycat:HarmlessQuestionableAnura',
        'gfycat:EnchantedWindingAegeancat',
        'gfycat:FlawlessThinInexpectatumpleco',
        'imgur:GaBLx9X',
        'imgur:ZOANMrO',
        'gfycat:ConsciousJollyChrysalis',
        'imgur:EOAYAsT',
        'gfycat:TameGrotesqueHarpyeagle',
        'imgur:b7EMEYu',
        'imgur:qmtPDEq',
        'gfycat:DefiniteFearlessCobra',
        'imgur:4XYMSLy',
        'imgur:9xKQTu7',
        'gfycat:PowerfulSecondArcticwolf',
        'imgur:J0s8Ks6',
        'imgur:UNvPoNC',
        'imgur:IOVbtql',
        'imgur:qclx6PM',
        'imgur:K1AuBC5',
        'imgur:oGLtuPr',
        'imgur:ONBKZaj',
        'imgur:dErnnAg',
        'gfycat:ObviousScratchyKingfisher',
        'gfycat:HotDesertedHerring',
        'gfycat:LegitimateSpectacularCygnet',
        'gfycat:CalmUniqueGroundbeetle',
        'gfycat:DarlingScholarlyEkaltadeta',
        'imgur:3dJYKU5',
        'imgur:XEClLfV',
        'imgur:0SxpxDf',
        'gfycat:PartialAliveAquaticleech',
        'gfycat:PinkJauntyCaiman',
        'imgur:PHd4Q0O',
        'gfycat:SomberFailingAsianpiedstarling',
        'gfycat:ShyUnawareBaldeagle',
        'imgur:CCBbzDD',
        'gfycat:DelightfulWavyAldabratortoise',
        'imgur:gO8PWQ4',
        'gfycat:LeanPortlyEagle',
        'imgur:fzfUKQa',
        'gfycat:TintedSophisticatedCanary',
        'gfycat:FatherlySparseCanary',
        'gfycat:AccurateFlickeringAchillestang',
        'gfycat:FabulousGargantuanDassie',
        'gfycat:ApprehensiveVerifiableKiwi',
        'gfycat:HonorableArcticAfricanclawedfrog',
        'gfycat:gifs/detail/FamiliarShimmeringAllensbigearedbat',
        'gfycat:gifs/detail/MatureWaryCapeghostfrog',
        'gfycat:DelightfulNaturalAmericanindianhorse',
        'gfycat:ClassicAngryFlickertailsquirrel',
        'gfycat:NippyNauticalAlaskajingle',
        'gfycat:DazzlingSmoggyAnnelid',
        'gfycat:ExcellentJauntyBeetle',
        'imgur:0lsA8l7',
        'gfycat:faithfullittlegallinule',
        'gfycat:TanGlaringAsiansmallclawedotter',
        'gfycat:KeenAridArgentinehornedfrog',
        'gfycat:ScholarlyWanHalcyon',
        'gfycat:FewNaiveArgali',
        'gfycat:RaggedHonoredIguanodon',
        'gfycat:SkinnyKeenCob',
        'gfycat:CarefulGrippingBellfrog',
        'gfycat:RightJealousKakarikis',
        'gfycat:NeighboringWateryAngora',
        'gfycat:RapidAnnualCarp',
        'gfycat:DecisiveIlliterateFieldmouse',
        'imgur:Bw2F5pZ',
        'imgur:JqJsbcg',
        'gfycat:AromaticVeneratedDaddylonglegs',
        'gfycat:ClassicAccurateArieltoucan',
        'gfycat:PhonyBelatedBushbaby',
        'gfycat:LonelyPeskyChafer',
        'gfycat:PleasedInsistentHypsilophodon',
        'gfycat:OblongOptimisticArthropods',
        'gfycat:DecentSociableAsianlion',
        'gfycat:PlainHappygoluckyCero',
        'gfycat:UltimateHoarseCheetah',
        'gfycat:WellwornSpitefulHake',
        'gfycat:ShabbyIncredibleGalapagosmockingbird',
        'gfycat:OldfashionedGraveEskimodog',
        'gfycat:DiligentSardonicGiraffe',
        'gfycat:CalmDiscreteCopperhead',
        'gfycat:InfamousIdenticalCuttlefish',
        'gfycat:ExcellentLonelyCuscus',
        'gfycat:ReliableBriefKodiakbear',

        'reddit:7olqwbd91x8a1',
        'reddit:074745vsrcy91',
        'reddit:2np9492tyki91',
        'reddit:16xxr0b5napa1',
        'reddit:s6pvmtrjbwe91',
        'reddit:1vqv35t9p6ia1',
        'reddit:37zshv8fykp91',
        'reddit:7sx1oiy3uzha1',
        'reddit:o481qmb1ff5a1',
        'reddit:m8k69ys4vkn91',
        '',
        '',



        

    ],
    justCause: [
        'imgur:trjS6g5',
        'gfycat:CorruptAdmiredIsabellineshrike',
        'gfycat:InnocentColossalCicada',
        'gfycat:BogusHappygoluckyAmurratsnake',
        'gfycat:DelightfulWaryGrebe',
        'gfycat:CheeryNaturalArrowworm',
        'gfycat:SevereContentDarklingbeetle',
        'gfycat:EvilPointedHapuka',
        'gfycat:PerkyPlasticAsp',
        'gfycat:MarvelousFluffyBlobfish',
        'gfycat:TenseInsistentChrysomelid',
        'gfycat:FailingEvergreenKingbird',
        'gfycat:AridBlondBarasingha',
        'imgur:v1ReynT',
        'gfycat:ScratchyJaggedHornet',
        'gfycat:TediousDependentEider',
        'gfycat:CompassionateMiniatureKestrel',
        'imgur:VP8jBPg',
        'gfycat:BewitchedDeliriousGibbon',
        'gfycat:HauntingSafeAntarcticfurseal',
        'gfycat:WarmColorfulJackal',
        'gfycat:HelplessUnevenGlassfrog',
        'gfycat:ThoughtfulFormalAmericanbadger',
        'imgur:TtVzQg2',
        'imgur:47zDmP3',
        'gfycat:CookedGargantuanGangesdolphin',
        'imgur:cWcpEIQ',
        '',
        '',
        '',



    ],
    kerbalSpaceProgram: [
        'gfycat:HarmoniousColossalHarrierhawk',
        'gfycat:WelloffIllinformedArcherfish',
        'gfycat:DiligentCourageousIberianmole',
        'gfycat:ThoseCostlyBorderterrier',
        'gfycat:YawningTameGelding',
        'gfycat:ActualOffbeatCollardlizard',
        'gfycat:AchingBelovedDevilfish',
        'gfycat:SaltyElegantGalapagostortoise',
        'gfycat:TestyBoringBoaconstrictor',
        'gfycat:SilverFlimsyBluetickcoonhound',
        'gfycat:WiltedRegularGermanspitz',
        'gfycat:WelltodoShrillDove',
        'gfycat:TerribleBlackGemsbok',
        'gfycat:MasculineCourageousAmericancreamdraft',
        'gfycat:IncomparableFabulousHylaeosaurus',
        'gfycat:TintedOblongGharial',
        'gfycat:CautiousHomelyIslandwhistler',
        'gfycat:UnequaledNauticalKookaburra',
        'gfycat:CleverGiganticGuineapig',
        'gfycat:CourteousForsakenIaerismetalmark',
        'gfycat:VainPaleBlueshark',
        'gfycat:RepentantVigilantAfricangoldencat',
        'gfycat:BaggyAgileAcornwoodpecker',
        'gfycat:WhichPiercingCob',
        'gfycat:FondQuestionableFlounder',
        'gfycat:WhoppingZealousDrake',
        'imgur:ksYF6L6',
        'gfycat:JaggedFixedGraywolf',
        'gfycat:GoldenGleefulCrustacean',
        'gfycat:QuarterlyWickedAsianconstablebutterfly',
        'imgur:CDSw1R3',
        'gfycat:PoisedIndolentAtlanticridleyturtle',
        'gfycat:SlightAmusingEsok',
        'gfycat:AngryCheerfulKangaroo',
        'gfycat:VagueSoggyKodiakbear',
        'gfycat:DetailedTestyBarasinga',
        'gfycat:FirstMeagerButterfly',
        'gfycat:NimbleClutteredEkaltadeta',
        'gfycat:ScentedKindlyIrukandjijellyfish',
        'gfycat:EnviousBlushingGibbon',
        'gfycat:AcidicRedApe',
        'imgur:3UEVYl3',
        'gfycat:CoarseDecentIcefish',
        'gfycat:VagueRecentCoqui',
        'gfycat:SmartYellowCockatiel',
        'gfycat:PrestigiousYoungAfricanaugurbuzzard',
        'gfycat:BelovedAnotherGoldeneye',
        'gfycat:SickNeglectedHaddock',
        'gfycat:HorribleNeedyBactrian',
        'gfycat:CanineOrneryHectorsdolphin',
        'gfycat:CreativeRichGreathornedowl',
        'gfycat:ShortHastyGiraffe',
        'gfycat:ViciousDependableHectorsdolphin',
        'gfycat:DistantSpicyBetafish',
        'gfycat:PolishedEssentialBlackbear',
        'gfycat:BestUnlinedElephantseal',
        'imgur:JnOS4nt',
        'gfycat:SatisfiedForthrightCassowary',
        'gfycat:PerfumedWideeyedFlickertailsquirrel',
        'gfycat:MiniatureWelllitBlackfootedferret',
        'gfycat:MassiveAdorableAkitainu',
        'gfycat:CoordinatedRemoteCowbird',
        '',
        '',
        '',
        '',


    ],
    overwatch: [
        'gfycat:AridGroundedBactrian',
        'gfycat:BaggyVictoriousIberianmole',
        'gfycat:BeneficialFlippantBelugawhale',
        'gfycat:BossyDistortedBudgie',
        'gfycat:BossyFlippantBlackfly',
        'gfycat:BreakableFairAxolotl',
        'gfycat:CanineScholarlyIbisbill',
        'gfycat:CaringFancyIndianspinyloach',
        'gfycat:CircularExaltedFlounder',
        'gfycat:CoarseSorrowfulCub',
        'gfycat:ConstantBreakableImperialeagle',
        'gfycat:ConstantObedientAfricanjacana',
        'gfycat:CreamyShyCottonmouth',
        'gfycat:DefensiveVillainousHammerkop',
        'gfycat:DeficientSmallEgret',
        'gfycat:DelectableRadiantKiwi',
        'gfycat:DependableGlassBee',
        'gfycat:DigitalOccasionalCygnet',
        'gfycat:EagerGoodGangesdolphin',
        'gfycat:EuphoricKindheartedIbis',
        'gfycat:FavorableRewardingAnura',
        'gfycat:FrankViciousHairstreak',
        'gfycat:FrighteningEmptyArgusfish',
        'gfycat:GeneralVeneratedGermanwirehairedpointer',
        'gfycat:GiftedFrenchAzurevase',
        'gfycat:GlassHappygoluckyArthropods',
        'gfycat:GoldenFreeGonolek',
        'gfycat:IdenticalPaltryAgama',
        'gfycat:ImpartialJitteryDuiker',
        'gfycat:ImpishDimAlbacoretuna',
        'gfycat:ImpressionableLargeIbizanhound',
        'gfycat:InfantileAdmiredDromedary',
        'gfycat:InfiniteImmediateIberianlynx',
        'gfycat:InstructiveMeanGuanaco',
        'gfycat:JampackedFreshHoopoe',
        'gfycat:LastingVacantBlackfish',
        'gfycat:LightDarkDrongo',
        'gfycat:LightheartedSmallEastrussiancoursinghounds',
        'gfycat:LonelyUntriedBluefish',
        'gfycat:MellowAnyHochstettersfrog',
        'gfycat:MellowBlackHoneybee',
        'gfycat:MerryNeglectedKinglet',
        'gfycat:MisguidedGlaringGrassspider',
        'gfycat:NaiveHopefulBergerpicard',
        'gfycat:NaturalWhisperedAfricanjacana',
        'gfycat:NecessaryGoldenDevilfish',
        'gfycat:NecessaryWastefulGuineafowl',
        'gfycat:OblongBewitchedBelugawhale',
        'gfycat:OldSpryFennecfox',
        'gfycat:OrneryIcyArcticwolf',
        'gfycat:PassionateGrandioseKinglet',
        'gfycat:PlainSecretGraysquirrel',
        'gfycat:PlumpIdioticKoalabear',
        'gfycat:PresentDisgustingAplomadofalcon',
        'gfycat:QuickImpartialKob',
        'gfycat:RedThirstyHeterodontosaurus',
        'gfycat:SaltyAggressiveCockerspaniel',
        'gfycat:SatisfiedSpiffyJaguar',
        'gfycat:ScrawnyDrearyDaddylonglegs',
        'gfycat:ShabbyAltruisticCreature',
        'gfycat:SleepyBreakableFrog',
        'gfycat:SmoggyQueasyFish',
        'gfycat:TestyWhichBuzzard',
        'gfycat:ThinColorfulAmericancrayfish',
        'gfycat:UnawareSorrowfulIndianglassfish',
        'gfycat:UnderstatedFearlessCoati',
        'gfycat:UnlinedEnchantingAsiansmallclawedotter',
        'gfycat:UnrealisticSilverFlamingo',
        'gfycat:UnripeVelvetyAmethystsunbird',
        'gfycat:UnsteadyCloseHedgehog',
        'gfycat:VerifiableTeemingAnemonecrab',
        'gfycat:WatchfulFreeCock',
        'gfycat:WeepyHonorableEasternnewt',
        'gfycat:WeightyLikableBrant',
        'gfycat:WeightyRealisticDwarfmongoose',
        'gfycat:WellwornTatteredEyra',
        'gfycat:ZigzagJealousIrishredandwhitesetter',
        'imgur:nHqy2FF',
        'imgur:Gw63577',
        'imgur:XRUjTjv',
        'imgur:oegdyME',
        'imgur:KXXcGMJ',
        'imgur:tLIzoE1',
        'imgur:6chBdw5',
        'imgur:To2UDdM',
        'imgur:GwnF00r',
        'gfycat:EquatorialAdeptHammerheadshark',
        'imgur:uy4C4I1',
        'gfycat:PoliteZanyGrouper',
        'imgur:WOutVGu',
        'gfycat:BackPoshHawaiianmonkseal',
        'gfycat:HandsomeUnimportantAngelfish',
        'gfycat:FaintGregariousKoala',
        'gfycat:TerribleFineHammerheadshark',

        'gfycat:InferiorPeskyAustraliankelpie',
        'gfycat:WhirlwindLonelyDachshund',
        'gfycat:GracefulUnconsciousAustraliankelpie',
        'gfycat:FluidIdenticalAmericanquarterhorse',
        'gfycat:MajorBlackandwhiteColt',
        'gfycat:AthleticLawfulCrab',
        'gfycat:InferiorAnguishedErmine',
        'gfycat:DeterminedZealousFossa',
        'gfycat:BaggyUniformHapuku',
        'gfycat:CreativeSpottedAcornbarnacle',
        'gfycat:TediousSnarlingJaguar',
        'gfycat:GivingRigidAtlasmoth',
        'gfycat:AmazingHighlevelKagu',
        'gfycat:PaleIndelibleGreatdane',
        'gfycat:WeeklySmartArmyworm',
        'gfycat:ShoddyBonyIndianpalmsquirrel',
        'gfycat:AchingImperturbableCaimanlizard',
        'gfycat:PassionateAdeptAfricanporcupine',
        'gfycat:PowerfulFavorableKangaroo',
        'gfycat:DarkNervousFinnishspitz',
        'gfycat:SnivelingObedientHousefly',
        'gfycat:NaughtyCleanEastsiberianlaika',
        'gfycat:DeafeningChubbyGroundhog',
        'gfycat:FelineWeeFireant',
        'gfycat:TerrificRequiredBlackandtancoonhound',
        'gfycat:RemorsefulSickGelding',
        'gfycat:LegitimateImpressionableArawana',
        'gfycat:AthleticLawfulCrab',
        'gfycat:RealUnawareBoilweevil',
        'gfycat:AssuredEmptyGerbil',
        'gfycat:SecretBlindAlpaca',
        'gfycat:NegligibleGracefulCowbird',
        'gfycat:PortlyVeneratedAnglerfish',
        'gfycat:BlindWarmBluet',
        'gfycat:BewitchedBaggyGartersnake',
        'gfycat:SaneAdorableBooby',
        'gfycat:JadedLeanGordonsetter',
        'gfycat:FamousPlainBlackrussianterrier',
        'gfycat:MeekVelvetyCanary',
        'gfycat:showytimelyislandcanary',
        'gfycat:GrossBlueBlackwidowspider',
        'gfycat:FantasticLateKakapo',
        'gfycat:RadiantDiscreteHart',
        'gfycat:DesertedCheeryKitten',
        'gfycat:InfatuatedEagerBedbug',
        'gfycat:SeveralRemoteGermanwirehairedpointer',
        'gfycat:DecimalTameAnnashummingbird',
        'gfycat:IcyBronzeGalapagostortoise',
        'gfycat:WhimsicalAlarmingBirdofparadise',
        'gfycat:MammothBigheartedGreatargus',
        'gfycat:FinishedDimwittedKitfox',
        'gfycat:LikableExhaustedHeterodontosaurus',
        'gfycat:SoreFloweryAmericansaddlebred',
        'gfycat:TerribleCluelessDowitcher',
        'gfycat:PopularMammothArchaeopteryx',


        'reddit:0e0svs468zwa1',
        'reddit:ulc0rpe1b00b1',
        'reddit:n9euc8tli9za1',
        'reddit:w0lno5fv1cva1',
        'reddit:wm4ow87njvba1',
        'reddit:haudb2sfdfba1',
        'reddit:bjry1vjo9z5a1',
        'reddit:ut899zsvu4oa1',
        'reddit:ljoqx3w2z2ya1',
        'reddit:xxyqkhwxmaca1',
        'reddit:t3pbk5lrxfwa1',
        'reddit:rlzzcq2o7fza1',
        'reddit:aslhwkf6i12b1',
        '',
        '',
        '',
        '',

    ],
    // other: [
    //     'imgur:P8MhFTn',
    //     'imgur:ICvySRr',
    //     'imgur:HNfYrDk',
    //     'imgur:ZbPU4D4',
    //     'imgur:pWKPmx7',
    //     'gfycat:DearFlawedAmericancreamdraft',
    //     'gfycat:AffectionateLeafyGermanwirehairedpointer',
    //     'imgur:Q8z3Wr9',
    //     'imgur:RRKKAdY',
    //     'imgur:u89VA7b',
    //     'imgur:b3kjvHm',
    // ],
    playerUnknownsBattleground: [
        'gfycat:LameWeeBluebreastedkookaburra',
        'imgur:4Urq78O',
        'gfycat:HugeImpartialDromedary',
        'imgur:0nXoUJV',
        'gfycat:SelfassuredIllinformedFairybluebird',
        'gfycat:WiltedPitifulGrizzlybear',
        'gfycat:MixedAcrobaticIvorybackedwoodswallow',
        'gfycat:GrouchyTalkativeGallinule',
        'imgur:7le1vsv',
        'gfycat:BeneficialDistantHellbender',
        'imgur:E0xxoom',
        'gfycat:EvilOptimisticDeinonychus',
        'gfycat:ForkedEntireHogget',
        'gfycat:LazyComplicatedFireant',
        'imgur:TMoJ9gd',
        'gfycat:InnocentThirdBedlingtonterrier',
        'gfycat:FamiliarWideBeauceron',
        'gfycat:ForsakenElaborateBarb',
        'gfycat:HomelyQuarrelsomeEstuarinecrocodile',
        'gfycat:ConventionalFirmIlladopsis',
        'gfycat:FabulousSorrowfulIbizanhound',
        'gfycat:OrderlyClosedBighornedsheep',
        'gfycat:PoliticalConstantAngwantibo',
        'gfycat:LightFloweryIsabellineshrike',
        'gfycat:QuestionableVictoriousHornshark',
        'gfycat:DarlingEducatedHectorsdolphin',
        'gfycat:WindyImmaculateDingo',
        'gfycat:WindingPeskyAustraliankelpie',
        'gfycat:MerryOrneryIslandwhistler',
        'gfycat:ImpishGrandioseAfricanharrierhawk',
        'gfycat:AdvancedVictoriousFossa',
        'gfycat:RaggedSeparateBighornedsheep',
        'gfycat:CarefulMammothGoat',
        'gfycat:SelfishDistortedDromaeosaur',
        'imgur:icELOuc',
        'gfycat:InstructiveUnimportantDunnart',
        'imgur:FfC5JH9',
        'imgur:fJ7rOfR',
        'gfycat:KindlyLameGlobefish',
        'gfycat:FixedWaryGreatwhiteshark',
        'gfycat:ImaginarySmoothChrysomelid',
        'gfycat:BleakWeepyAlbacoretuna',
        'gfycat:MagnificentLiquidAttwatersprairiechicken',
        'gfycat:VariableQuickGermanpinscher',
        'imgur:MHa9Aki',
        '',


    ],
    // retro : [
    //         'imgur:Ey1svIG',
    //         'imgur:MAUJ9qs',
    //         'imgur:6LqGq3I',
    //         'gfycat:AstonishingChillyBubblefish',
    //         'imgur:wuvKDUi',
    //         'gfycat:HandyDigitalCoypu',
    //         'gfycat:SameAptIndianabat',
    //         'gfycat:SeparateBiodegradableGiantschnauzer',
    //         'gfycat:AbleFlakyIndianrhinoceros',
    //         'gfycat:HonorableCanineDikkops',
    //         'gfycat:IlliterateSomberBasil',
    //         'gfycat:ImportantIdioticJerboa',
    //         'gfycat:ElementaryLongFirebelliedtoad',
    //         'gfycat:UniqueMarvelousCowrie',
    //         'gfycat:KindlySeparateBlackpanther',
    //         'imgur:ymAqmrW',
    //         'gfycat:BlueMemorableHairstreakbutterfly',
    //         'gfycat:AstonishingChillyBubblefish',
    //         'imgur:QyyKCpc',
    //         'imgur:TtJroYn',
    //         'imgur:uN4lbXC',
    //         'imgur:tTSEKI8',
    //         'imgur:BrXlTUM',
    //         'imgur:r4JfLnc',
    //         'imgur:MAUJ9qs',
    //         'imgur:cppiUt3',
    //         '',
    //         '',
    //         '',
    //         '',


    //     ],    
    rocketLeague: [
        'gfycat:ElderlyThreadbareHuemul',
        'imgur:IRhpB15',
        'gfycat:ConfusedElderlyBorzoi',
        'gfycat:ShadyImprobableIberianbarbel',
        'gfycat:GreedyLimitedBalloonfish',
        'gfycat:DenseSarcasticDogwoodtwigborer',
        'gfycat:LankyEsteemedBoar',
        'imgur:whZaccO',
        '',
        '',
        '',


    ],
    starWarsBattlefront: [
        'imgur:iCmlLGx',
        'imgur:3Mt4ZeF',
        'imgur:GbqTyxo',
        'imgur:sdWJZIU',
        'imgur:fc8xuJF',
        'imgur:kBmAcOb',
        'imgur:uew7nPZ',
        'imgur:ab3ozjc',
        'imgur:VsH86oF',
        'imgur:NQvNlFi',
        'gfycat:ArtisticDecimalKingfisher',
        'imgur:ikfmYbC',
        'gfycat:UnacceptableIdleDevilfish',
        'gfycat:LargeRewardingHalibut',
        'gfycat:VillainousGraveIberianlynx',
        'imgur:AFWpVTh',
        'imgur:fNLeQfT',
        'imgur:btRMgfO',
        'gfycat:ShortUnlinedHarborporpoise',
        'gfycat:LimpWavyCougar',
        'gfycat:OnlyAnotherCollardlizard',
        'gfycat:InnocentOpulentKitty',
        'gfycat:PinkSeriousHalibut',
        'gfycat:WeeBetterBongo',
        'gfycat:QuickFaintCheetah',
        'gfycat:SecretGargantuanCoqui',
        'gfycat:UnselfishWavyErne',
        '',
        '',


    ],
    // teamFortress2: [
    //     'gfycat:ImperturbableTintedHorse'
    // ],
    // vr : [
    //     'imgur:vBxA52M',
    //     '',
    //     '',

    // ],
    witcher3: [
        'gfycat:LeanFlawedIberianchiffchaff',
        'imgur:nnQsyej',
        'gfycat:RegalIncredibleIrrawaddydolphin',
        'gfycat:GregariousPresentDutchshepherddog',
        'gfycat:VioletCarelessDinosaur',
        'gfycat:EquatorialEvergreenIchthyosaurs',
        'gfycat:BitesizedRemarkableIchthyosaurs',
        'gfycat:HappygoluckyMaleChicken',
        'gfycat:EvergreenRepentantBluejay',
        'gfycat:ReasonableRepentantLabradorretriever',
        'gfycat:AdolescentInfamousKiskadee',
        'gfycat:SparseHauntingHumpbackwhale',
        'gfycat:WickedSpiffyFulmar',
        'gfycat:TediousUnimportantDorado',
        'imgur:YdFUEtN',
        '',
        '',
        '',
        '',

    ],
    warframe: [
        'reddit:t7n0oowz1xva1',
        'reddit:lkt4b68mc5j91',
        'reddit:7yqos5wu9d0b1',
        'reddit:geztx3frl9na1',
        '',
        '',
        '',
        '',
        '',
        '',

    ],
    worldOfWarcraft: [

        'imgur:agZISAX',

        'imgur:JAZClBI',
    ],









}